language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - "cpanm --installdeps ."
    - "cpanm Devel::Cover::Report::Coveralls"
script:
  perl Makefile.PL && make test && cover -test -report coveralls
